// Grade 1 kanji with meanings
const grade1Kanji = [
  { c: "一", m: "one" },
  { c: "右", m: "right" },
  { c: "雨", m: "rain" },
  { c: "円", m: "circle, yen" },
  { c: "王", m: "king" },
  { c: "音", m: "sound" },
  { c: "下", m: "below, down" },
  { c: "火", m: "fire" },
  { c: "花", m: "flower" },
  { c: "貝", m: "shell" },
  { c: "学", m: "study, learning" },
  { c: "気", m: "spirit, energy" },
  { c: "九", m: "nine" },
  { c: "休", m: "rest" },
  { c: "玉", m: "ball, jewel" },
  { c: "金", m: "gold, money" },
  { c: "空", m: "sky, empty" },
  { c: "月", m: "moon, month" },
  { c: "犬", m: "dog" },
  { c: "見", m: "see" },
  { c: "五", m: "five" },
  { c: "口", m: "mouth" },
  { c: "校", m: "school" },
  { c: "左", m: "left" },
  { c: "三", m: "three" },
  { c: "山", m: "mountain" },
  { c: "子", m: "child" },
  { c: "四", m: "four" },
  { c: "糸", m: "thread" },
  { c: "字", m: "character" },
  { c: "耳", m: "ear" },
  { c: "七", m: "seven" },
  { c: "車", m: "car" },
  { c: "手", m: "hand" },
  { c: "十", m: "ten" },
  { c: "出", m: "exit" },
  { c: "女", m: "woman" },
  { c: "小", m: "small" },
  { c: "上", m: "above, up" },
  { c: "森", m: "forest" },
  { c: "人", m: "person" },
  { c: "水", m: "water" },
  { c: "正", m: "correct" },
  { c: "生", m: "life" },
  { c: "青", m: "blue" },
  { c: "夕", m: "evening" },
  { c: "石", m: "stone" },
  { c: "赤", m: "red" },
  { c: "千", m: "thousand" },
  { c: "川", m: "river" },
  { c: "先", m: "before, ahead" },
  { c: "早", m: "early" },
  { c: "草", m: "grass" },
  { c: "足", m: "foot, leg" },
  { c: "村", m: "village, town" },
  { c: "大", m: "big, large" },
  { c: "男", m: "man" },
  { c: "竹", m: "bamboo" },
  { c: "中", m: "middle" },
  { c: "虫", m: "insect" },
  { c: "町", m: "town, village, block" },
  { c: "天", m: "heaven" },
  { c: "田", m: "rice field" },
  { c: "土", m: "soil, earth" },
  { c: "二", m: "two" },
  { c: "日", m: "day, sun" },
  { c: "入", m: "enter" },
  { c: "年", m: "year" },
  { c: "白", m: "white" },
  { c: "八", m: "eight" },
  { c: "百", m: "hundred" },
  { c: "文", m: "text, writing, sentence, literature" },
  { c: "木", m: "tree, wood" },
  { c: "本", m: "book, origin" },
  { c: "名", m: "name" },
  { c: "目", m: "eye" },
  { c: "立", m: "stand" },
  { c: "力", m: "power" },
  { c: "林", m: "woods" },
  { c: "六", m: "six" },
];

// Grade 2 kanji with meanings
const grade2Kanji = [
  { c: "引", m: "pull" },
  { c: "羽", m: "feather" },
  { c: "雲", m: "cloud" },
  { c: "園", m: "garden" },
  { c: "遠", m: "far" },
  { c: "何", m: "what" },
  { c: "科", m: "subject, course" },
  { c: "夏", m: "summer" },
  { c: "家", m: "house, home" },
  { c: "歌", m: "song" },
  { c: "画", m: "picture" },
  { c: "回", m: "-times, round, revolve, counter for occurrences" },
  { c: "会", m: "meeting" },
  { c: "海", m: "sea" },
  { c: "絵", m: "painting" },
  { c: "外", m: "outside" },
  { c: "角", m: "angle, corner" },
  { c: "楽", m: "comfort, music" },
  { c: "活", m: "lively, active" },
  { c: "間", m: "interval, space" },
  { c: "丸", m: "circle, round" },
  { c: "岩", m: "rock" },
  { c: "顔", m: "face" },
  { c: "汽", m: "steam" },
  { c: "記", m: "record" },
  { c: "帰", m: "return, homecoming, arrive at" },
  { c: "弓", m: "bow" },
  { c: "牛", m: "cow" },
  { c: "魚", m: "fish" },
  { c: "京", m: "capital" },
  { c: "強", m: "strong" },
  { c: "教", m: "teach" },
  { c: "近", m: "near" },
  { c: "兄", m: "elder brother" },
  { c: "形", m: "shape, form, style" },
  { c: "計", m: "measure" },
  { c: "元", m: "beginning, former time, origin" },
  { c: "言", m: "say" },
  { c: "原", m: "field, plain" },
  { c: "戸", m: "door" },
  { c: "古", m: "old" },
  { c: "午", m: "noon, sign of the horse" },
  { c: "後", m: "behind, back, later, after" },
  { c: "語", m: "language, speech" },
  { c: "工", m: "craft, construction" },
  { c: "公", m: "public" },
  { c: "広", m: "wide" },
  { c: "交", m: "exchange" },
  { c: "光", m: "light" },
  { c: "考", m: "think" },
  { c: "行", m: "go" },
  { c: "高", m: "high" },
  { c: "黄", m: "yellow" },
  { c: "合", m: "fit, suit, join" },
  { c: "谷", m: "valley" },
  { c: "国", m: "country" },
  { c: "黒", m: "black" },
  { c: "今", m: "now" },
  { c: "才", m: "talent" },
  { c: "細", m: "thin" },
  { c: "作", m: "make" },
  { c: "算", m: "calculate" },
  { c: "止", m: "stop" },
  { c: "市", m: "market, city, town" },
  { c: "矢", m: "arrow" },
  { c: "姉", m: "elder sister" },
  { c: "思", m: "think" },
  { c: "紙", m: "paper" },
  { c: "寺", m: "temple" },
  { c: "自", m: "self" },
  { c: "時", m: "time" },
  { c: "室", m: "room, apartment" },
  { c: "社", m: "company, society" },
  { c: "弱", m: "weak" },
  { c: "首", m: "neck" },
  { c: "秋", m: "autumn" },
  { c: "週", m: "week" },
  { c: "春", m: "spring" },
  { c: "書", m: "write" },
  { c: "少", m: "few" },
  { c: "場", m: "place" },
  { c: "色", m: "color" },
  { c: "食", m: "eat" },
  { c: "心", m: "heart" },
  { c: "新", m: "new" },
  { c: "親", m: "parent" },
  { c: "図", m: "map, drawing" },
  { c: "数", m: "number" },
  { c: "西", m: "west" },
  { c: "声", m: "voice" },
  { c: "星", m: "star" },
  { c: "晴", m: "clear weather" },
  { c: "切", m: "cut" },
  { c: "雪", m: "snow" },
  { c: "船", m: "ship" },
  { c: "線", m: "line" },
  { c: "前", m: "in front, before" },
  { c: "組", m: "group" },
  { c: "走", m: "run" },
  { c: "多", m: "many" },
  { c: "太", m: "thick" },
  { c: "体", m: "body" },
  { c: "台", m: "pedestal, a stand, counter for machines and vehicles" },
  { c: "地", m: "ground, earth" },
  { c: "池", m: "pond" },
  { c: "知", m: "know" },
  { c: "茶", m: "tea" },
  { c: "昼", m: "daytime, noon" },
  { c: "長", m: "long" },
  { c: "鳥", m: "bird" },
  { c: "朝", m: "morning" },
  { c: "直", m: "straight, honesty, fix, repair" },
  { c: "通", m: "pass through" },
  { c: "弟", m: "younger brother" },
  { c: "店", m: "store" },
  { c: "点", m: "point" },
  { c: "電", m: "electricity" },
  { c: "刀", m: "sword" },
  { c: "冬", m: "winter" },
  { c: "当", m: "hit, right" },
  { c: "東", m: "east" },
  { c: "答", m: "answer" },
  { c: "頭", m: "head" },
  { c: "同", m: "same" },
  { c: "道", m: "road, way" },
  { c: "読", m: "read" },
  { c: "内", m: "inside" },
  { c: "南", m: "south" },
  { c: "肉", m: "meat" },
  { c: "馬", m: "horse" },
  { c: "売", m: "sell" },
  { c: "買", m: "buy" },
  { c: "麦", m: "wheat" },
  { c: "半", m: "half" },
  { c: "番", m: "number, turn" },
  { c: "父", m: "father" },
  { c: "風", m: "wind" },
  { c: "分", m: "part, minute" },
  { c: "聞", m: "hear" },
  { c: "米", m: "rice" },
  { c: "歩", m: "walk" },
  { c: "母", m: "mother" },
  { c: "方", m: "direction, way" },
  { c: "北", m: "north" },
  { c: "毎", m: "every" },
  { c: "妹", m: "younger sister" },
  { c: "万", m: "ten thousand" },
  { c: "明", m: "bright" },
  { c: "鳴", m: "chirp, sound" },
  { c: "毛", m: "hair, fur" },
  { c: "門", m: "gate" },
  { c: "夜", m: "night" },
  { c: "野", m: "field" },
  { c: "友", m: "friend" },
  { c: "用", m: "utilize, business, service, use, employ" },
  { c: "曜", m: "day of week" },
  { c: "来", m: "come" },
  { c: "里", m: "ri, village, parent's home" },
  { c: "理", m: "reason" },
  { c: "話", m: "talk" },
];

// Grade 3 kanji with meanings
const grade3Kanji = [
  { c: "悪", m: "bad, evil" },
  { c: "安", m: "peaceful" },
  { c: "暗", m: "dark" },
  { c: "医", m: "doctor, medicine" },
  { c: "委", m: "committee" },
  { c: "意", m: "meaning" },
  { c: "育", m: "raise, grow" },
  { c: "員", m: "member" },
  { c: "院", m: "institution" },
  { c: "飲", m: "drink" },
  { c: "運", m: "carry, luck" },
  { c: "泳", m: "swim" },
  { c: "駅", m: "station" },
  { c: "央", m: "center" },
  { c: "横", m: "side, horizontal" },
  { c: "屋", m: "roof, shop" },
  { c: "温", m: "warm" },
  { c: "化", m: "change" },
  { c: "荷", m: "luggage" },
  { c: "界", m: "world" },
  { c: "開", m: "open" },
  { c: "階", m: "floor, story" },
  { c: "寒", m: "cold" },
  { c: "感", m: "feeling" },
  { c: "漢", m: "Chinese" },
  { c: "館", m: "building" },
  { c: "岸", m: "shore" },
  { c: "起", m: "wake up" },
  { c: "期", m: "period" },
  { c: "客", m: "guest" },
  { c: "究", m: "research" },
  { c: "急", m: "urgent" },
  { c: "級", m: "class, rank" },
  { c: "宮", m: "shrine, palace" },
  { c: "球", m: "ball" },
  { c: "去", m: "leave" },
  { c: "橋", m: "bridge" },
  { c: "業", m: "business" },
  { c: "曲", m: "curve, music" },
  { c: "局", m: "bureau" },
  { c: "銀", m: "silver" },
  { c: "区", m: "district" },
  { c: "苦", m: "suffering" },
  { c: "具", m: "tool" },
  { c: "君", m: "you" },
  { c: "係", m: "connection" },
  { c: "軽", m: "light" },
  { c: "血", m: "blood" },
  { c: "決", m: "decide" },
  { c: "研", m: "sharpen, study" },
  { c: "県", m: "prefecture" },
  { c: "庫", m: "warehouse" },
  { c: "湖", m: "lake" },
  { c: "向", m: "facing" },
  { c: "幸", m: "happiness" },
  { c: "港", m: "harbor" },
  { c: "号", m: "number" },
  { c: "根", m: "root" },
  { c: "祭", m: "festival" },
  { c: "皿", m: "plate" },
  { c: "仕", m: "serve" },
  { c: "死", m: "death" },
  { c: "使", m: "use" },
  { c: "始", m: "begin" },
  { c: "指", m: "finger, point" },
  { c: "歯", m: "tooth" },
  { c: "詩", m: "poem" },
  { c: "次", m: "next" },
  { c: "事", m: "matter" },
  { c: "持", m: "hold" },
  { c: "式", m: "ceremony" },
  { c: "実", m: "reality" },
  { c: "写", m: "copy" },
  { c: "者", m: "person" },
  { c: "主", m: "main" },
  { c: "守", m: "protect" },
  { c: "取", m: "take" },
  { c: "酒", m: "alcohol" },
  { c: "受", m: "receive" },
  { c: "州", m: "state" },
  { c: "拾", m: "pick up" },
  { c: "終", m: "end" },
  { c: "習", m: "learn" },
  { c: "集", m: "gather" },
  { c: "住", m: "live, dwell" },
  { c: "重", m: "heavy" },
  { c: "宿", m: "lodge" },
  { c: "所", m: "place" },
  { c: "暑", m: "hot" },
  { c: "助", m: "help" },
  { c: "昭", m: "bright" },
  { c: "消", m: "extinguish" },
  { c: "商", m: "commerce" },
  { c: "章", m: "chapter" },
  { c: "勝", m: "win" },
  { c: "乗", m: "ride" },
  { c: "植", m: "plant" },
  { c: "申", m: "say" },
  { c: "身", m: "body" },
  { c: "神", m: "god" },
  { c: "真", m: "true" },
  { c: "深", m: "deep" },
  { c: "進", m: "advance" },
  { c: "世", m: "world, generation" },
  { c: "整", m: "arrange" },
  { c: "昔", m: "long ago" },
  { c: "全", m: "all" },
  { c: "相", m: "mutual" },
  { c: "送", m: "send" },
  { c: "想", m: "think" },
  { c: "息", m: "breath" },
  { c: "速", m: "fast" },
  { c: "族", m: "tribe, family" },
  { c: "他", m: "other" },
  { c: "打", m: "hit" },
  { c: "対", m: "opposite" },
  { c: "待", m: "wait" },
  { c: "代", m: "substitute" },
  { c: "第", m: "ordinal number" },
  { c: "題", m: "topic" },
  { c: "炭", m: "charcoal" },
  { c: "短", m: "short" },
  { c: "談", m: "discuss" },
  { c: "着", m: "wear" },
  { c: "注", m: "pour" },
  { c: "柱", m: "pillar" },
  { c: "丁", m: "town section" },
  { c: "帳", m: "notebook" },
  { c: "調", m: "tone, investigate" },
  { c: "追", m: "chase" },
  { c: "定", m: "determine" },
  { c: "庭", m: "garden" },
  { c: "笛", m: "flute" },
  { c: "鉄", m: "iron" },
  { c: "転", m: "revolve" },
  { c: "都", m: "metropolis" },
  { c: "度", m: "degree" },
  { c: "投", m: "throw" },
  { c: "豆", m: "bean" },
  { c: "島", m: "island" },
  { c: "湯", m: "hot water" },
  { c: "登", m: "climb" },
  { c: "等", m: "etc." },
  { c: "動", m: "move" },
  { c: "童", m: "child" },
  { c: "農", m: "agriculture" },
  { c: "波", m: "wave" },
  { c: "配", m: "distribute" },
  { c: "倍", m: "double" },
  { c: "箱", m: "box" },
  { c: "畑", m: "field" },
  { c: "発", m: "departure" },
  { c: "反", m: "anti-" },
  { c: "坂", m: "slope" },
  { c: "板", m: "board" },
  { c: "皮", m: "skin" },
  { c: "悲", m: "sad" },
  { c: "美", m: "beauty" },
  { c: "鼻", m: "nose" },
  { c: "筆", m: "brush" },
  { c: "氷", m: "ice" },
  { c: "表", m: "table, surface" },
  { c: "秒", m: "second" },
  { c: "病", m: "illness" },
  { c: "品", m: "goods" },
  { c: "負", m: "lose" },
  { c: "部", m: "part" },
  { c: "服", m: "clothes" },
  { c: "福", m: "luck" },
  { c: "物", m: "thing" },
  { c: "平", m: "flat" },
  { c: "返", m: "return" },
  { c: "勉", m: "diligence" },
  { c: "放", m: "release" },
  { c: "味", m: "taste" },
  { c: "命", m: "life, command" },
  { c: "面", m: "face" },
  { c: "問", m: "question" },
  { c: "役", m: "role" },
  { c: "薬", m: "medicine" },
  { c: "由", m: "reason" },
  { c: "油", m: "oil" },
  { c: "有", m: "have" },
  { c: "遊", m: "play" },
  { c: "予", m: "beforehand" },
  { c: "羊", m: "sheep" },
  { c: "洋", m: "ocean, western" },
  { c: "葉", m: "leaf" },
  { c: "陽", m: "sunshine" },
  { c: "様", m: "manner" },
  { c: "落", m: "fall" },
  { c: "流", m: "flow" },
  { c: "旅", m: "travel" },
  { c: "両", m: "both" },
  { c: "緑", m: "green" },
  { c: "礼", m: "bow, thanks" },
  { c: "列", m: "row" },
  { c: "練", m: "practice" },
  { c: "路", m: "road" },
  { c: "和", m: "peace, Japanese" },
];

// Grade 4 kanji with meanings
const grade4Kanji = [
  { c: "愛", m: "love" },
  { c: "案", m: "plan" },
  { c: "以", m: "by means of" },
  { c: "衣", m: "clothing" },
  { c: "位", m: "rank" },
  { c: "囲", m: "surround" },
  { c: "胃", m: "stomach" },
  { c: "印", m: "stamp" },
  { c: "英", m: "England, English" },
  { c: "栄", m: "prosperity" },
  { c: "塩", m: "salt" },
  { c: "億", m: "hundred million" },
  { c: "加", m: "add" },
  { c: "果", m: "fruit" },
  { c: "貨", m: "freight" },
  { c: "課", m: "section" },
  { c: "芽", m: "bud" },
  { c: "改", m: "reform" },
  { c: "械", m: "machinery" },
  { c: "害", m: "harm" },
  { c: "街", m: "street" },
  { c: "各", m: "each" },
  { c: "覚", m: "memorize" },
  { c: "完", m: "complete" },
  { c: "官", m: "government" },
  { c: "管", m: "pipe" },
  { c: "関", m: "connection" },
  { c: "観", m: "view" },
  { c: "願", m: "request" },
  { c: "希", m: "hope" },
  { c: "季", m: "season" },
  { c: "紀", m: "chronicle" },
  { c: "喜", m: "rejoice" },
  { c: "旗", m: "flag" },
  { c: "器", m: "container" },
  { c: "機", m: "machine" },
  { c: "議", m: "deliberation" },
  { c: "求", m: "request" },
  { c: "泣", m: "cry" },
  { c: "救", m: "rescue" },
  { c: "給", m: "salary" },
  { c: "挙", m: "raise" },
  { c: "漁", m: "fishing" },
  { c: "共", m: "together" },
  { c: "協", m: "cooperation" },
  { c: "鏡", m: "mirror" },
  { c: "競", m: "compete" },
  { c: "極", m: "extreme" },
  { c: "訓", m: "instruction" },
  { c: "軍", m: "army" },
  { c: "郡", m: "county" },
  { c: "径", m: "diameter" },
  { c: "型", m: "type" },
  { c: "景", m: "scenery" },
  { c: "芸", m: "art" },
  { c: "欠", m: "lack" },
  { c: "結", m: "tie" },
  { c: "建", m: "build" },
  { c: "健", m: "healthy" },
  { c: "験", m: "test" },
  { c: "固", m: "solid" },
  { c: "功", m: "achievement" },
  { c: "好", m: "like" },
  { c: "候", m: "climate" },
  { c: "航", m: "navigation" },
  { c: "康", m: "health" },
  { c: "告", m: "tell" },
  { c: "差", m: "difference" },
  { c: "菜", m: "vegetable" },
  { c: "最", m: "most" },
  { c: "材", m: "material" },
  { c: "昨", m: "yesterday" },
  { c: "札", m: "tag" },
  { c: "刷", m: "printing" },
  { c: "殺", m: "kill" },
  { c: "察", m: "inspect" },
  { c: "参", m: "participate" },
  { c: "産", m: "production" },
  { c: "散", m: "scatter" },
  { c: "残", m: "remain" },
  { c: "士", m: "warrior" },
  { c: "氏", m: "surname" },
  { c: "史", m: "history" },
  { c: "司", m: "director" },
  { c: "試", m: "test" },
  { c: "児", m: "child" },
  { c: "治", m: "cure" },
  { c: "辞", m: "resign" },
  { c: "失", m: "lose" },
  { c: "借", m: "borrow" },
  { c: "種", m: "seed" },
  { c: "周", m: "circumference" },
  { c: "祝", m: "celebrate" },
  { c: "順", m: "order" },
  { c: "初", m: "first" },
  { c: "松", m: "pine tree" },
  { c: "笑", m: "laugh" },
  { c: "唱", m: "chant" },
  { c: "焼", m: "burn" },
  { c: "象", m: "elephant" },
  { c: "照", m: "illuminate" },
  { c: "賞", m: "prize" },
  { c: "臣", m: "retainer" },
  { c: "信", m: "trust" },
  { c: "成", m: "become" },
  { c: "省", m: "ministry" },
  { c: "清", m: "pure" },
  { c: "静", m: "quiet" },
  { c: "席", m: "seat" },
  { c: "積", m: "accumulate" },
  { c: "折", m: "fold" },
  { c: "節", m: "node, season" },
  { c: "説", m: "theory" },
  { c: "浅", m: "shallow" },
  { c: "戦", m: "war" },
  { c: "選", m: "choose" },
  { c: "然", m: "so" },
  { c: "争", m: "conflict" },
  { c: "倉", m: "warehouse" },
  { c: "巣", m: "nest" },
  { c: "束", m: "bundle" },
  { c: "側", m: "side" },
  { c: "続", m: "continue" },
  { c: "卒", m: "graduate" },
  { c: "孫", m: "grandchild" },
  { c: "帯", m: "belt" },
  { c: "隊", m: "group" },
  { c: "達", m: "attain" },
  { c: "単", m: "simple" },
  { c: "置", m: "place" },
  { c: "仲", m: "relationship" },
  { c: "貯", m: "savings" },
  { c: "兆", m: "trillion" },
  { c: "腸", m: "intestines" },
  { c: "低", m: "low" },
  { c: "底", m: "bottom" },
  { c: "停", m: "stop" },
  { c: "的", m: "target" },
  { c: "典", m: "code" },
  { c: "伝", m: "transmit" },
  { c: "徒", m: "follower" },
  { c: "努", m: "toil" },
  { c: "灯", m: "lamp" },
  { c: "堂", m: "hall" },
  { c: "働", m: "work" },
  { c: "特", m: "special" },
  { c: "得", m: "acquire" },
  { c: "毒", m: "poison" },
  { c: "熱", m: "heat" },
  { c: "念", m: "thought" },
  { c: "敗", m: "defeat" },
  { c: "梅", m: "plum" },
  { c: "博", m: "exhibition" },
  { c: "飯", m: "meal" },
  { c: "飛", m: "fly" },
  { c: "費", m: "expense" },
  { c: "必", m: "necessary" },
  { c: "票", m: "ballot" },
  { c: "標", m: "mark" },
  { c: "不", m: "not" },
  { c: "夫", m: "husband" },
  { c: "付", m: "attach" },
  { c: "府", m: "prefecture" },
  { c: "副", m: "vice-" },
  { c: "粉", m: "powder" },
  { c: "兵", m: "soldier" },
  { c: "別", m: "separate" },
  { c: "辺", m: "area" },
  { c: "変", m: "change" },
  { c: "便", m: "convenience" },
  { c: "包", m: "wrap" },
  { c: "法", m: "law" },
  { c: "望", m: "hope" },
  { c: "牧", m: "pasture" },
  { c: "末", m: "end" },
  { c: "満", m: "full" },
  { c: "未", m: "not yet" },
  { c: "脈", m: "pulse" },
  { c: "民", m: "people" },
  { c: "無", m: "nothing" },
  { c: "約", m: "promise" },
  { c: "勇", m: "courage" },
  { c: "要", m: "need" },
  { c: "養", m: "nurture" },
  { c: "浴", m: "bathe" },
  { c: "利", m: "profit" },
  { c: "陸", m: "land" },
  { c: "良", m: "good" },
  { c: "料", m: "fee" },
  { c: "量", m: "quantity" },
  { c: "輪", m: "wheel" },
  { c: "類", m: "type" },
  { c: "令", m: "order" },
  { c: "冷", m: "cold" },
  { c: "例", m: "example" },
  { c: "歴", m: "history" },
  { c: "連", m: "connect" },
  { c: "老", m: "old" },
  { c: "労", m: "labor" },
  { c: "録", m: "record" },
];

// Grade 5 kanji with meanings
const grade5Kanji = [
  { c: "圧", m: "pressure" },
  { c: "移", m: "move" },
  { c: "因", m: "cause" },
  { c: "永", m: "eternity" },
  { c: "営", m: "manage" },
  { c: "衛", m: "defense" },
  { c: "易", m: "easy" },
  { c: "益", m: "benefit" },
  { c: "液", m: "liquid" },
  { c: "演", m: "perform" },
  { c: "応", m: "respond" },
  { c: "往", m: "journey" },
  { c: "桜", m: "cherry blossom" },
  { c: "恩", m: "kindness" },
  { c: "可", m: "possible" },
  { c: "仮", m: "temporary" },
  { c: "価", m: "value" },
  { c: "河", m: "river" },
  { c: "過", m: "exceed" },
  { c: "賀", m: "congratulations" },
  { c: "快", m: "pleasant" },
  { c: "解", m: "solution" },
  { c: "格", m: "status" },
  { c: "確", m: "certain" },
  { c: "額", m: "amount" },
  { c: "刊", m: "publish" },
  { c: "幹", m: "trunk" },
  { c: "慣", m: "custom" },
  { c: "眼", m: "eye" },
  { c: "基", m: "foundation" },
  { c: "寄", m: "contribute" },
  { c: "規", m: "rule" },
  { c: "技", m: "skill" },
  { c: "義", m: "righteousness" },
  { c: "逆", m: "reverse" },
  { c: "久", m: "long time" },
  { c: "旧", m: "old times" },
  { c: "居", m: "reside" },
  { c: "許", m: "permit" },
  { c: "境", m: "boundary" },
  { c: "均", m: "equal" },
  { c: "禁", m: "prohibition" },
  { c: "句", m: "phrase" },
  { c: "群", m: "group" },
  { c: "経", m: "passage" },
  { c: "潔", m: "clean" },
  { c: "件", m: "matter" },
  { c: "券", m: "ticket" },
  { c: "険", m: "danger" },
  { c: "検", m: "examine" },
  { c: "限", m: "limit" },
  { c: "現", m: "present" },
  { c: "減", m: "decrease" },
  { c: "故", m: "reason" },
  { c: "個", m: "individual" },
  { c: "護", m: "protect" },
  { c: "効", m: "effect" },
  { c: "厚", m: "thick" },
  { c: "耕", m: "till" },
  { c: "鉱", m: "mineral" },
  { c: "構", m: "construct" },
  { c: "興", m: "interest" },
  { c: "講", m: "lecture" },
  { c: "混", m: "mix" },
  { c: "査", m: "investigate" },
  { c: "再", m: "again" },
  { c: "災", m: "disaster" },
  { c: "妻", m: "wife" },
  { c: "採", m: "pick" },
  { c: "際", m: "occasion" },
  { c: "在", m: "exist" },
  { c: "財", m: "wealth" },
  { c: "罪", m: "crime" },
  { c: "雑", m: "miscellaneous" },
  { c: "酸", m: "acid" },
  { c: "賛", m: "approve" },
  { c: "支", m: "support" },
  { c: "志", m: "intention" },
  { c: "枝", m: "branch" },
  { c: "師", m: "teacher" },
  { c: "資", m: "resources" },
  { c: "飼", m: "raise animals" },
  { c: "示", m: "show" },
  { c: "似", m: "resemble" },
  { c: "識", m: "knowledge" },
  { c: "質", m: "quality" },
  { c: "舎", m: "cottage" },
  { c: "謝", m: "apologize" },
  { c: "授", m: "impart" },
  { c: "修", m: "discipline" },
  { c: "述", m: "state" },
  { c: "術", m: "art, technique" },
  { c: "準", m: "standard" },
  { c: "序", m: "preface" },
  { c: "招", m: "invite" },
  { c: "承", m: "consent" },
  { c: "証", m: "evidence" },
  { c: "条", m: "article" },
  { c: "状", m: "condition" },
  { c: "常", m: "usual" },
  { c: "情", m: "emotion" },
  { c: "織", m: "weave" },
  { c: "職", m: "job" },
  { c: "制", m: "system" },
  { c: "性", m: "gender, nature" },
  { c: "政", m: "politics" },
  { c: "勢", m: "forces" },
  { c: "精", m: "refined" },
  { c: "製", m: "manufacture" },
  { c: "税", m: "tax" },
  { c: "責", m: "responsibility" },
  { c: "績", m: "achievements" },
  { c: "接", m: "contact" },
  { c: "設", m: "establish" },
  { c: "舌", m: "tongue" },
  { c: "絶", m: "extinction" },
  { c: "銭", m: "coin" },
  { c: "祖", m: "ancestor" },
  { c: "素", m: "element" },
  { c: "総", m: "whole" },
  { c: "造", m: "create" },
  { c: "像", m: "image" },
  { c: "増", m: "increase" },
  { c: "則", m: "rule" },
  { c: "測", m: "measure" },
  { c: "属", m: "belong" },
  { c: "率", m: "rate" },
  { c: "損", m: "loss" },
  { c: "退", m: "retreat" },
  { c: "貸", m: "lend" },
  { c: "態", m: "attitude" },
  { c: "団", m: "group" },
  { c: "断", m: "cut off" },
  { c: "築", m: "build" },
  { c: "張", m: "stretch" },
  { c: "提", m: "propose" },
  { c: "程", m: "extent" },
  { c: "適", m: "suitable" },
  { c: "敵", m: "enemy" },
  { c: "統", m: "unite" },
  { c: "銅", m: "copper" },
  { c: "導", m: "guide" },
  { c: "徳", m: "virtue" },
  { c: "独", m: "alone" },
  { c: "任", m: "responsibility" },
  { c: "燃", m: "burn" },
  { c: "能", m: "ability" },
  { c: "破", m: "break" },
  { c: "犯", m: "crime" },
  { c: "判", m: "judge" },
  { c: "版", m: "edition" },
  { c: "比", m: "compare" },
  { c: "肥", m: "fertilizer" },
  { c: "非", m: "negative" },
  { c: "備", m: "provide" },
  { c: "俵", m: "sack" },
  { c: "評", m: "evaluate" },
  { c: "貧", m: "poor" },
  { c: "布", m: "cloth" },
  { c: "婦", m: "lady" },
  { c: "富", m: "wealth" },
  { c: "武", m: "military" },
  { c: "復", m: "restore" },
  { c: "複", m: "complex" },
  { c: "仏", m: "Buddha" },
  { c: "編", m: "compile" },
  { c: "弁", m: "valve" },
  { c: "保", m: "preserve" },
  { c: "墓", m: "grave" },
  { c: "報", m: "report" },
  { c: "豊", m: "abundant" },
  { c: "防", m: "prevent" },
  { c: "貿", m: "trade" },
  { c: "暴", m: "violence" },
  { c: "務", m: "duty" },
  { c: "夢", m: "dream" },
  { c: "迷", m: "astray" },
  { c: "綿", m: "cotton" },
  { c: "輸", m: "transport" },
  { c: "余", m: "surplus" },
  { c: "預", m: "deposit" },
  { c: "容", m: "contain" },
  { c: "略", m: "abbreviation" },
  { c: "留", m: "stay" },
  { c: "領", m: "territory" },
];

// Combine all grades
const kanji = [
  ...grade1Kanji.map((k) => ({ ...k, grade: 1 })),
  ...grade2Kanji.map((k) => ({ ...k, grade: 2 })),
  ...grade3Kanji.map((k) => ({ ...k, grade: 3 })),
  ...grade4Kanji.map((k) => ({ ...k, grade: 4 })),
  ...grade5Kanji.map((k) => ({ ...k, grade: 5 })),
].map((kanji) => ({ character: kanji.c, meaning: kanji.m, grade: kanji.grade }));

// Parse kanji data from grades 1-5
const parseKanjiData = () => kanji;

module.exports = {
  parseKanjiData,
};
