// w - word, m - meaning
const words = [
    { w: "水道", r: "すいどう", m: "water supply / faucet" },
    { w: "電気", r: "でんき", m: "electricity" },
    { w: "曜日", r: "ようび", m: "day of the week" },
    { w: "天気", r: "てんき", m: "weather" },
    { w: "昼ごはん", r: "ひるごはん", m: "lunch" },
    { w: "食べ物", r: "たべもの", m: "food" },
    { w: "肉屋", r: "にくや", m: "butcher" },
    { w: "朝ごはん", r: "あさごはん", m: "breakfast" },
    { w: "夕方", r: "ゆうがた", m: "evening" },
    { w: "父母", r: "ふぼ", m: "parents" },
    { w: "姉妹", r: "しまい", m: "sisters" },
    { w: "兄弟", r: "きょうだい", m: "siblings" },
    { w: "友だち", r: "ともだち", m: "friend" },
    { w: "学校", r: "がっこう", m: "school" },
    { w: "先生", r: "せんせい", m: "teacher" },
    { w: "会社", r: "かいしゃ", m: "company" },
    { w: "電車", r: "でんしゃ", m: "train" },
    { w: "道", r: "みち", m: "road / path" },
    { w: "子ども", r: "こども", m: "child" },
    { w: "父", r: "ちち", m: "father" },
    { w: "母", r: "はは", m: "mother" },
    { w: "兄", r: "あに", m: "older brother" },
    { w: "弟", r: "おとうと", m: "younger brother" },
    { w: "姉", r: "あね", m: "older sister" },
    { w: "妹", r: "いもうと", m: "younger sister" },
    { w: "名前", r: "なまえ", m: "name" },
    { w: "毎日", r: "まいにち", m: "every day" },
    { w: "大人", r: "おとな", m: "adult" },
    { w: "赤ちゃん", r: "あかちゃん", m: "baby" },
    { w: "国", r: "くに", m: "country" },
    { w: "年", r: ["とし", "ねん"], m: "year / age" },
    { w: "月", r: ["つき", "がつ"], m: "month" },
    { w: "日", r: ["ひ", "にち"], m: "day" },
    { w: "生まれ", r: "うまれ", m: "birth" },
    { w: "会話", r: "かいわ", m: "conversation" },
    { w: "書く", r: "かく", m: "to write" },
    { w: "体", r: "からだ", m: "body" },
    { w: "手", r: "て", m: "hand" },
    { w: "足", r: "あし", m: "foot / leg" },
    { w: "目", r: "め", m: "eye" },
    { w: "耳", r: "みみ", m: "ear" },
    { w: "口", r: "くち", m: "mouth" },
    { w: "心", r: "こころ", m: "heart (mental/emotional)" },
    { w: "風", r: "かぜ", m: "cold / wind" },
    { w: "気", r: "き", m: "spirit / energy (as in 元気)" },
    { w: "仕事", r: "しごと", m: "job / work" },
    { w: "社会", r: "しゃかい", m: "society" },
    { w: "話す", r: "はなす", m: "to speak" },
    { w: "聞く", r: "きく", m: "to listen / ask" },
    { w: "会う", r: "あう", m: "to meet" },
    { w: "読む", r: "よむ", m: "to read" },
    { w: "買い物", r: "かいもの", m: "shopping" },
    { w: "店", r: "みせ", m: "store" },
    { w: "売る", r: "うる", m: "to sell" },
    { w: "買う", r: "かう", m: "to buy" },
    { w: "本屋", r: "ほんや", m: "bookstore" },
    { w: "肉", r: "にく", m: "meat" },
    { w: "米", r: ["こめ", "ごはん"], m: "rice" },
    { w: "八百屋", r: "やおや", m: "vegetable shop" },
    { w: "円", r: "えん", m: "yen" },
    { w: "物", r: "もの", m: "thing" },
    { w: "春", r: "はる", m: "spring" },
    { w: "夏", r: "なつ", m: "summer" },
    { w: "秋", r: "あき", m: "autumn" },
    { w: "冬", r: "ふゆ", m: "winter" },
    { w: "雪", r: "ゆき", m: "snow" },
    { w: "風", r: "かぜ", m: "wind" },
    { w: "空", r: "そら", m: "sky" },
    { w: "日", r: "ひ", m: "sun / day" },
    { w: "月", r: "つき", m: "moon" },
    { w: "晴れ", r: "はれ", m: "clear weather" },
    { w: "朝", r: "あさ", m: "morning" },
    { w: "昼", r: "ひる", m: "noon" },
    { w: "夜", r: "よる", m: "night" },
    { w: "食べる", r: "たべる", m: "to eat" },
    { w: "歩く", r: "あるく", m: "to walk" },
    { w: "出かける", r: "でかける", m: "to go out" },
    { w: "入る", r: "はいる", m: "to enter (e.g., bath, room)" },
    { w: "好き", r: "すき", m: "like" },
    { w: "大好き", r: "だいすき", m: "love" },
    { w: "元気", r: "げんき", m: "healthy / well" },
    { w: "楽しい", r: "たのしい", m: "fun / enjoyable" },
    { w: "思う", r: "おもう", m: "to think" },
    { w: "家", r: ["いえ", "うち"], m: "home" },
    { w: "町", r: "まち", m: "town" },
    { w: "山", r: "やま", m: "mountain" },
    { w: "川", r: "かわ", m: "river" },
    { w: "中", r: "なか", m: "inside" },
    { w: "今日", r: "きょう", m: "today" },
    { w: "明日", r: "あした", m: "tomorrow" },
    { w: "昨日", r: "きのう", m: "yesterday" },
    { w: "今", r: "いま", m: "now" },
    { w: "前", r: "まえ", m: "before / earlier" },
    { w: "後", r: "あと", m: "after / later" },
    { w: "時", r: "とき", m: "time / moment" },
    { w: "行く", r: "いく", m: "to go" },
    { w: "来る", r: "くる", m: "to come" },
    { w: "出る", r: "でる", m: "to leave / go out" },
    { w: "立つ", r: "たつ", m: "to stand" },
    { w: "座る", r: "すわる", m: "to sit" },
    { w: "見る", r: "みる", m: "to see / look" },
    { w: "飲む", r: "のむ", m: "to drink" },
    { w: "走る", r: "はしる", m: "to run" },
    { w: "使う", r: "つかう", m: "to use" },
    { w: "休む", r: "やすむ", m: "to rest / take a break" },
    { w: "働く", r: "はたらく", m: "to work" },
    { w: "乗る", r: "のる", m: "to ride (a vehicle)" },
    { w: "通う", r: "かよう", m: "to commute" },
    { w: "通学", r: "つうがく", m: "commuting to school" },
    { w: "通る", r: "とおる", m: "to pass / go through" },
    { w: "船", r: "ふね", m: "boat" },
    { w: "駅", r: "えき", m: "station" },
    { w: "車", r: "くるま", m: "car" }
]

const parseWordData = () => words.map((word) => ({ word: word.w, reading: word.r, meaning: word.m }));;

module.exports = {
  parseWordData,
};